package main

import (
	"io/ioutil"
	"os"
	"strings"
	"testing"
)

func TestDownloadFile(t *testing.T) {
	// Create a temporary directory for testing
	tempDir, err := ioutil.TempDir("", "test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tempDir)

	// Create a temporary file for testing
	tempFile, err := ioutil.TempFile(tempDir, "testfile")
	if err != nil {
		t.Fatal(err)
	}
	defer tempFile.Close()

	// Define the URL, filepath, and filename for testing
	url := "https://example.com/file.txt"
	filepath := tempDir
	filename := "testfile.txt"

	// Call the downloadFile function
	err = downloadFile(url, filepath, filename)
	if err != nil {
		t.Errorf("downloadFile returned an error: %v", err)
	}

	// Verify that the file was downloaded successfully
	_, err = os.Stat(filepath + "/" + filename)
	if err != nil {
		t.Errorf("downloaded file does not exist: %v", err)
	}
}
func TestValidateFile(t *testing.T) {
	// Create a temporary directory for testing
	tempDir, err := ioutil.TempDir("", "test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tempDir)

	// Create a temporary file for testing
	tempFile, err := ioutil.TempFile(tempDir, "testfile")
	if err != nil {
		t.Fatal(err)
	}
	defer tempFile.Close()

	// Get the actual filename generated by ioutil.TempFile - its the last item if we split on /
	filename := strings.Split(tempFile.Name(), "/")[3]

	// Write test data to the temporary file
	testData := []byte("test data")
	_, err = tempFile.Write(testData)
	if err != nil {
		t.Fatal(err)
	}

	// Define the filepath and expected sha256sum for testing
	filepath := tempDir
	expectedSum := "916f0027a575074ce72a331777c3478d6513f786a591bd892da1a577bf2335f9"

	// Call the validateFile function
	err = validateFile(filepath, filename, expectedSum)
	if err != nil {
		t.Errorf("validateFile returned an error: %v", err)
	}
}
